### ISSUE TITLE
Unknown system on a new Ubuntu 14.04 box in AWS

### ISSUE THREAD

**Issue by pauldambra** [jordansissel/pleaserun#78] opened 2015-03-30 13:46 UTC
I've installed facter and its output looks like:

```
architecture => amd64
blockdevice_xvda_size => 32212254720
blockdevices => xvda
facterversion => 1.7.5
filesystems => ext2,ext3,ext4,iso9660,vfat
hardwareisa => x86_64
hardwaremodel => x86_64
id => ubuntu
is_virtual => true
kernel => Linux
kernelmajversion => 3.13
kernelrelease => 3.13.0-44-generic
kernelversion => 3.13.0
lsbdistcodename => trusty
lsbdistdescription => Ubuntu 14.04.2 LTS
lsbdistid => Ubuntu
lsbdistrelease => 14.04
lsbmajdistrelease => 14
memoryfree => 932.70 MB
memoryfree_mb => 932.70
memorysize => 992.47 MB
memorysize_mb => 992.47
memorytotal => 992.47 MB
mtu_eth0 => 9001
mtu_lo => 65536
operatingsystem => Ubuntu
operatingsystemrelease => 14.04
osfamily => Debian
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
physicalprocessorcount => 1
processor0 => Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
processorcount => 1
ps => ps -ef
rubysitedir => /usr/local/lib/site_ruby/1.9.1
rubyversion => 1.9.3
selinux => false
swapfree => 0.00 MB
swapfree_mb => 0.00
swapsize => 0.00 MB
swapsize_mb => 0.00
timezone => UTC
uniqueid => 1facc510
uptime => 4:53 hours
uptime_days => 0
uptime_hours => 4
uptime_seconds => 17590
virtual => xenu
```

and installed pleaserun in the hope I can use it to install EventStore.

If I `sudo pleaserun --install /eventstore-3.0.1/run-node.sh`

the output is:

/var/lib/gems/1.9.1/gems/pleaserun-0.0.12/lib/pleaserun/detector.rb:47:in `detect': true  (PleaseRun::Detector::UnknownSystem)
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.12/lib/pleaserun/cli.rb:140:in `setup_defaults'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.12/lib/pleaserun/cli.rb:107:in `execute'
	from /var/lib/gems/1.9.1/gems/clamp-0.6.4/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/1.9.1/gems/clamp-0.6.4/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.12/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'

Did I do something silly? Is there something I could do to work up a pullrequest to fix? (I'm pretty new to linux but learning so willing to put some time in if you provide a pointer)

**Comment by pauldambra** [comment] 2015-03-30 13:51
If I run `sudo pleaserun --install -p upstart -v 1.5 --name eventstore /eventstore-3.0.1/run-node.sh` all seems to work OK.

**Comment by pauldambra** [comment] 2015-03-30 13:57
Oh!
````
:~$ facter operatingsystem
Ubuntu
:~$ facter operatingsystemrelease
14.04
````

but in Detecter.rb 

````
  def self.lookup(platform_and_version)
    return MAPPING[platform_and_version]
  end
````

Is that a case sensitive lookup? If so that'd explain the failure.

**Comment by jordansissel** [comment] 2015-05-01 00:19
```
root@asdf:~# pleaserun asdf
/var/lib/gems/1.9.1/gems/pleaserun-0.0.13/lib/pleaserun/detector.rb:47:in `detect': true  (PleaseRun::Detector::UnknownSystem)
```

Confirmed this fails under `facter`, but succeeds with `ohai`.

**Comment by jordansissel** [comment] 2015-05-01 00:21
Strangely, Facter.fact["operatingsystem"] is returning `true`, not a string like "Ubuntu"

**Comment by jordansissel** [comment] 2015-05-01 00:23
@pauldambra What version of facter are you using? Check `facter --version` - I wonder if the API in facter changed that caused this problem. (Facter 2 was released in the last year, I am betting this is the cause)

**Comment by jordansissel** [comment] 2015-05-01 00:28
Alternately, it's possible that facter support _never_worked in pleaserun.

I tested with the latest Facter 1 (1.7.6) and Facter 2 (2.4.3). Both fail when invoked as `Facter.fact["somefact"]` because `Facter.fact` is a method taking an argument, oops.

I see the bug, I defined `detect_facter` twice:
* https://github.com/jordansissel/pleaserun/blob/3ea9dd9184273cbef7b7200708208d39f993db07/lib/pleaserun/detector.rb#L70-L76
* https://github.com/jordansissel/pleaserun/blob/3ea9dd9184273cbef7b7200708208d39f993db07/lib/pleaserun/detector.rb#L93

This explains why the "platform" is true, because `require "facter"` returns true and that is returned from the `detect_facter` method.

Oops! This will be an easy fix.

**Comment by jordansissel** [comment] 2016-05-18 04:32
I think this is fixed now because the platform detector was rewritten and no longer needs facter or ohai to guess the best platform. Instead, the detector looks for signs of various platforms (systemctl for systemd, initctl for upstart, etc) to determine what platforms are available.

Hope this helps! Let me know if you continue to have problems.

**Closed by jordansissel** 2016-05-18 04:32 UTC
